export const AUDIT_ACTIONS = {
    // Auth
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
    LOGOUT:"LOGOUT",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAILED:"REGISTER_FAILED",
    TOKEN_REFRESH:"TOKEN_REFRESH",

    // Future — add as needed
    // PASSWORD_CHANGE:     "PASSWORD_CHANGE",
    // PROFILE_UPDATE:      "PROFILE_UPDATE",
    // PRODUCT_CREATED:     "PRODUCT_CREATED",
    // PRODUCT_UPDATED:     "PRODUCT_UPDATED",
    // PRODUCT_DELETED:     "PRODUCT_DELETED",
    // ORDER_PLACED:        "ORDER_PLACED",
    // ORDER_STATUS_CHANGE: "ORDER_STATUS_CHANGE",
};